### ISSUE TITLE
Date sorting seems to be off

### ISSUE THREAD

**Issue by bbarker** [singularityhub/sregistry-cli#135]
For instance, at https://www.singularity-hub.org/collections/1220#, the July 17 2018 entry will sometimes appear in between July 6 and July 16.

**Comment by vsoch** [comment]
Thanks, I will look into this for the next round of edits! I think this is likely because the sorting is isn't really set to be anything in particular other than a general string for the column. If you are in dire need, the files metadata for each container has a full timestamp for when it was created, for example --> https://www.singularity-hub.org/api/containers/3557/

**Comment by vsoch** [comment]
oh hey @bbarker this is in the wrong repo (oups!) would you re-open (and referencing to here is ok) on the one for Singularity Hub? --> https://github.com/singularityhub/singularityhub.github.io/issues

Thank you!
