### ISSUE TITLE
Compatibility between cli and sregistry versions?

### ISSUE THREAD

**Issue by Trophime** [singularityhub/sregistry-cli#213]
Hi, 
I wonder if there is some compatibility issue with sregistry-cli version and sregistry version.
I've tried to push an image with 0.1.39 cli version to a 0.0.94 sregistry and  I got:

sregistry search 
[client|registry] [database|sqlite:////home/LNCMI-G/trophime/.singularity/sregistry.db]
ERROR The server returned a malformed response.

Best
C

**Comment by vsoch** [comment]
What do the server logs say? (docker-compose logs)

**Comment by vsoch** [comment]
There was an update of sregistry server (a while back) to use the Nginx upload module, so if you didn’t update your server you will need to use an earlier version of the client.

**Comment by vsoch** [comment]
Did you just update the client? If so, go back to the previous version.

**Comment by Trophime** [comment]
The previous version is indeed working!

**Comment by vsoch** [comment]
Also, are you not able to communicate with whomever runs your server? They can give you a more direct response about if there’s a change.

**Comment by Trophime** [comment]
The server used to be was administred by @victorsndvg ...
But I don't know who is in charge of it right now.
I'm checking that

**Comment by vsoch** [comment]
Great! What happened to @victorsndvg? He used to post on here a lot and it's been a while.

To give you some docs about the changes you are seeing, a little less than a year ago the server was upload to use the [nginx upload module](https://github.com/singularityhub/sregistry/pull/134) which allows for much faster uploads.

And of course on the same date the client was [also updated](https://github.com/singularityhub/sregistry-cli/pull/127). You are getting that message because you have a client sending a ping to an endpoint that doesn't exist, and the fix is to keep your version of sregistry cli less than 0.0.88.

**Comment by victorsndvg** [comment]
Dear @vsoch and @Trophime ,

I'm no longer working for the project/institution  which I've to use/deploy sregistry. This means that I don't have access/rights to administer services ...

Anyway, @Trophime  I remember that I containerize `sregistry` to freeze the working version at that moment. If you take a look to the registry, you are going to see several `sregistry` versions. `0.0.94` and  `0.0.98` versions are available, and probably `latest` is the recomended version to interact with the registry

Hope to helpful.

Best regards!

**Comment by Trophime** [comment]
Thanks @victorsndvg 
indeed it works fine with your sregistry image ;)

Best

**Comment by vsoch** [comment]
Safe and fun journeys ahead @victorsndvg ! It's been a pleasure working with you these last few years.
