### ISSUE TITLE
Mixing sregistry and spython problems

### ISSUE THREAD

**Issue by tschoonj** [singularityhub/sregistry-cli#232]
**Describe the bug**

Hi @vsoch!

In one of my Python scripts I am creating Singularity images in a for loop, with each image being built on top of the previous one.

I am running into trouble when building the second image, as I noticed that `sudo singularity build` is then invoked with the `--quiet` parameter, which is an issue for me since my sudo privileges do not allow this. I was wondering why this happened because I nowhere asked for quiet mode and figured out that this happens after the first image is created with `spython.main.Client.build`, when I add the image to my local database with my sregistry client, which appears to set the spython client quiet attribute to True, when running inspect:

https://github.com/singularityhub/sregistry-cli/blob/54c0c3ed18a4bae005863ae706e1b07b37a6297f/sregistry/main/base/inspect.py#L58-L63

My suggestion is to fix this in sregistry by saving the current quiet attribute value before calling inspect, and restoring it afterwards.

**To Reproduce**

A bit complicated to reduce to a couple of lines  so I recommend to have a look at https://github.com/DiamondLightSource/Savu/blob/c3677cf69a3be0247d517aa76907bae136d100cc/singularity-recipes/mass-rebuild.py, which is where I am using this.

**Version of Singularity and Singularity Registry Client**

Singularity version: 2.6.1
Singularity Registry version: 0.2.25
Singularity CLI version: 0.0.73

I hope this is clear, let me know if you need to know anything else!

**Comment by vsoch** [comment]
Yes this totally makes sense! And it's just an oversight. Give me a few minutes to PR.

**Comment by vsoch** [comment]
This is awesome! Would you be open to adding this to the sregistry docs (either the web or README) in just a list of examples of using the client? Maybe adding to the README is logical, and then linking to from the docs?

**Comment by tschoonj** [comment]
Glad you like my script... Feel free to link to it from the docs, but you may want to wait until the PR it is in, gets merged in.

**Comment by vsoch** [comment]
Can do! Can you send me a note when it's in tip top shape?

**Comment by tschoonj** [comment]
Certainly, but there may be more changes coming up soon as I may need to split the image builds up into separate jobs in the workflow, simply to avoid the 60 minutes build timeout. Or even move the whole thing to Azure at some point, as the timeout there is 6 hours. This is all mostly proof of concept at the moment...

Thanks again for all the help, this would not have been possible without your hard work!

**Comment by vsoch** [comment]
Not to throw another cloud provider into the mix - but have you tried Google Cloud Bulld? The current https://containers.page is using it, and there is a version that also works from the command line. The current PR #231 actually adds timeout as a variable (because default is 10 minutes, and I set it to three hours). The units are seconds, and if I remember correctly, the max timeout for Google Cloud Build is 24 hours.

And no worries we can add it whenever it's good!

**Comment by tschoonj** [comment]
No I haven't actually... Thanks for the advice!

**Comment by vsoch** [comment]
Sure thing! I've played around with it a bunch, so let me know if you want to know tricks. What containers.page does is to first clone a repo, then target a recipe to build, and send back a response. The one detail I haven't set up is their notifications (via pub sub) so if you work on that, let's chat about it because I haven't done it yet.

**Comment by vsoch** [comment]
And also setting up whatever their secrets server / method is, I rolled my own but I'm sure it's not as good.
