### ISSUE TITLE
How can I make a limited user use the container read-only?

### ISSUE THREAD

**Issue by hpcs-isaka** [singularityhub/sregistry-cli#245]
To make a limited user use the container read-only, I tried following.

1. Create a collection in private but not public on sregistry WebUI.
2. Upload a singularity container file to the collection.

In this state, I understand that other users will not be able to upload to the collection with sregistry-cli, and will not be displayed even if the container is searched with the 'sregistry search' command.
Then, even if I register other user on the team in the WebUI, the container will not display if the user searches using sregistry search. Also, the user will be able to upload containers. That is not what I want.

What I want to do is let other users search for containers in the private collection without having them upload.
Is there a way to somehow prevent other users from uploading and let them display the container using the 'sregistry search' command?

**Comment by vsoch** [comment]
I don't totally understand your question - if it's related to Singularity Registry server you'd want to post it to https://github.com/singularityhub/sregistry/issues. If it's related to the client, then here is good :)

Basically, for a user to see a private collection, they must be an owner or contributor. That's why it's private. If they are a contributor, they shouldn't be able to upload, but they should be able to search. If you have an example of the functionality that isn't desired (actual commands, users executing them, and the permission / roles in the collections) and the exact output I can better debug this for you, but likely later in the week, so no rush.
